//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music.Net_App.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumSong
    {
        public int AlbumSongID { get; set; }
        public Nullable<int> AlbumID { get; set; }
        public Nullable<int> SongID { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Song Song { get; set; }
    }
}
