//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music.Net_App.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListeningHistory
    {
        public int ListenID { get; set; }
        public Nullable<int> ListenerID { get; set; }
        public Nullable<int> ArtistID { get; set; }
        public string ItemType { get; set; }
        public int ItemID { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Listener Listener { get; set; }
    }
}
