//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music.Net_App.DAL.Viet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Album()
        {
            this.AlbumSongs = new HashSet<AlbumSong>();
        }
    
        public int AlbumID { get; set; }
        public Nullable<int> ArtistID { get; set; }
        public Nullable<int> GenreID { get; set; }
        public string AlbumName { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<int> PopularityScore { get; set; }
        public Nullable<int> Duration { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Genre Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlbumSong> AlbumSongs { get; set; }
    }
}
