//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music.Net_App.DAL.Viet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Playlist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Playlist()
        {
            this.PlaylistSongs = new HashSet<PlaylistSong>();
        }
    
        public int PlaylistID { get; set; }
        public Nullable<int> ListenerID { get; set; }
        public Nullable<int> ArtistID { get; set; }
        public string PlaylistTyped { get; set; }
        public string PlaylistName { get; set; }
        public string Descriptions { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> PopularityScore { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Listener Listener { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaylistSong> PlaylistSongs { get; set; }
    }
}
